version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/demo
    overwrite: true
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
  AfterInstall:
    - location: scripts/application_start.sh
      timeout: 300
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300