version: 0.0
os: linux
variables:
  user: ec2-user
  appName: demo
files:
  - source: /
    destination: home/ec2-user/demo
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root
    - location: scripts/application_start .sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
      runas: root